/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matricesstring;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author YO
 */
public class MostrarDatos extends javax.swing.JFrame {

    /**
     * Creates new form MostrarDatos
     */
    public MostrarDatos() {
        initComponents();
        
        //ORUEBA!!
        //pruebaCAMBIO
        jButton2.setVisible(false);
        txtB1.setVisible(false);
        txtB2.setVisible(false);
        txtB3.setVisible(false);
        txtB4.setVisible(false);
        txtB5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtB1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtB2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtB3 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtB4 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtB5 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        jLabel1.setText("Nombre");

        jLabel2.setText("Sueldo BASE");

        jLabel3.setText("Total DD");

        jLabel4.setText("Total PP");

        jLabel5.setText("Dep.");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "20,000"},
                {"2", "30,000"},
                {"3", "10,000"},
                {"4", "15,000"},
                {"5", "25,000"}
            },
            new String [] {
                "N", "Dep."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton2.setText("Liquidos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtB1.setColumns(20);
        txtB1.setRows(5);
        jScrollPane3.setViewportView(txtB1);

        txtB2.setColumns(20);
        txtB2.setRows(5);
        jScrollPane4.setViewportView(txtB2);

        txtB3.setColumns(20);
        txtB3.setRows(5);
        jScrollPane5.setViewportView(txtB3);

        txtB4.setColumns(20);
        txtB4.setRows(5);
        jScrollPane6.setViewportView(txtB4);

        txtB5.setColumns(20);
        txtB5.setRows(5);
        jScrollPane7.setViewportView(txtB5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(jScrollPane6))
                                .addGap(105, 105, 105))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane7))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        jButton2.setVisible(true);
        
        if( jTextField1.equals("") || jTextField2.equals("") || jTextField3.equals("") || jTextField4.equals("") || jTextField5.equals("") ){
            System.out.println("error no todas llenas");
        }else{
            
            String[][] M = new String[5][5];
            int rand1, rand2,rand3,rand4; 
            
            M[0][0]=jTextField1.getText();M[0][1]=jTextField2.getText();M[0][2]=jTextField3.getText();M[0][3]=jTextField4.getText();M[0][4]=jTextField5.getText();
            
            for(int i=0; i<=4; i++){
                rand1=(int)(Math.random()*3000+2000);
                M[1][i]=""+rand1;
                
                rand2=(int)(Math.random()*1000+500);
                M[2][i]=""+rand2;
                
                rand3=(int)(Math.random()*2000+1000);
                M[3][i]=""+rand3;
                
                rand4=(int)(Math.random()*5+1);
                M[4][i]=""+rand4;
                
            }
            
            for(int i=0; i<=4; i++){
                for(int j=0; j<=4; j++){
                    txtA.setText(txtA.getText()+""+M[j][i]+"\t");
                 }
                txtA.setText(txtA.getText()+"\n");
            }
            
            int[] Deps=new int[5];
            Deps[0]=Integer.parseInt(M[4][0]);Deps[1]=Integer.parseInt(M[4][1]);Deps[2]=Integer.parseInt(M[4][2]);Deps[3]=Integer.parseInt(M[4][3]);Deps[4]=Integer.parseInt(M[4][4]);
            
            txtB1.setText("Departamento #1:\n");txtB2.setText("Departamento #2:\n");txtB3.setText("Departamento #3:\n");txtB4.setText("Departamento #4:\n");txtB5.setText("Departamento #5:\n");
            
            
            for(int i=0; i<=4; i++){
                    double tot1,tot2,tot3,tot4,tot5;
                    if(Deps[i]==1){
                        
                        txtB1.setText(txtB1.getText()+"\n NOMBRE:\t"+M[0][i]+"\n (+)SUELDO BASE:\t"+M[1][i]+"\n (+)DEDUCCIONES \t   "+M[2][i]+"\n(+)TOTAL PP\t "+M[3][i]+"\n(+)DEPARTAMENTO:\t 20,000");
                        
                        int sld = Integer.parseInt(M[1][i]);
                        double iggs = (Integer.parseInt(M[1][i]))*(0.0483);
                        
                        double ISR;
                        if(sld>2600 && sld<5000){
                            ISR = sld*0.03;
                        }else{
                            if(sld>5000 && sld<10000){
                                ISR = sld*0.05;
                            }else{
                                ISR = sld*0.10;
                            }
                        }
                        
                        txtB1.setText(txtB1.getText()+"\n(-)ISR:  "+ISR+"");txtB1.setText(txtB1.getText()+"\n(-)IGGS:  "+iggs);
                        
                        tot1=(Integer.parseInt(M[1][i]))+(Integer.parseInt(M[2][i]))+(Integer.parseInt(M[3][i]))+20000-ISR-iggs;
                        txtB1.setText(txtB1.getText()+"\nTOTAL LIQUIDO:  "+tot1+"\n");
                    }else{
                        if(Deps[i]==2){
                            txtB2.setText(txtB2.getText()+"\n NOMBRE:\t"+M[0][i]+"\n (+)SUELDO BASE:\t"+M[1][i]+"\n (+)DEDUCCIONES \t   "+M[2][i]+"\n(+)TOTAL PP\t "+M[3][i]+"\n(+)DEPARTAMENTO:\t 30,000");
                            
                            int sld = Integer.parseInt(M[1][i]);
                            double iggs = (Integer.parseInt(M[1][i]))*(0.0483);
                            double ISR;
                           if(sld>2600 && sld<5000){
                              ISR = sld*0.03;
                           }else{
                                if(sld>5000 && sld<10000){
                                    ISR = sld*0.05;
                             }else{
                                   ISR = sld*0.10;
                              }
                             }
                           
                                txtB2.setText(txtB2.getText()+"\nISR:  "+ISR+"\n");txtB2.setText(txtB2.getText()+"\nIGGS:  "+iggs+"\n");
                                tot2=(Integer.parseInt(M[1][i]))+(Integer.parseInt(M[2][i]))+(Integer.parseInt(M[3][i]))+30000-ISR-iggs;
                            txtB2.setText(txtB2.getText()+"\nTOTAL LIQUIDO:  "+tot2+"\n");
                        }else{
                            if(Deps[i]==3){
                                txtB3.setText(txtB3.getText()+"\n NOMBRE:\t"+M[0][i]+"\n (+)SUELDO BASE:\t"+M[1][i]+"\n (+)DEDUCCIONES \t   "+M[2][i]+"\n(+)TOTAL PP\t "+M[3][i]+"\n(+)DEPARTAMENTO:\t 10,000");
                                
                                    int sld = Integer.parseInt(M[1][i]);
                                    double iggs = (Integer.parseInt(M[1][i]))*(0.0483);
                                    
                                    double ISR;
                                   if(sld>2600 && sld<5000){
                                      ISR = sld*0.03;
                                   }else{
                                        if(sld>5000 && sld<10000){
                                            ISR = sld*0.05;
                                     }else{
                                           ISR = sld*0.10;
                                      }
                                     }
                                   
                                txtB3.setText(txtB3.getText()+"\nISR:  "+ISR+"\n");txtB3.setText(txtB3.getText()+"\nIGGS:  "+iggs+"\n");
                                tot3=(Integer.parseInt(M[1][i]))+(Integer.parseInt(M[2][i]))+(Integer.parseInt(M[3][i]))+10000-ISR-iggs;
                                txtB3.setText(txtB3.getText()+"\nTOTAL LIQUIDO:  "+tot3+"\n");
                                
                            }else{
                                if(Deps[i]==4){
                                    txtB4.setText(txtB4.getText()+"\n NOMBRE:\t"+M[0][i]+"\n (+)SUELDO BASE:\t"+M[1][i]+"\n (+)DEDUCCIONES \t   "+M[2][i]+"\n(+)TOTAL PP\t "+M[3][i]+"\n(+)DEPARTAMENTO:\t 15,000");
                                    
                                        int sld = Integer.parseInt(M[1][i]);
                                        double iggs = (Integer.parseInt(M[1][i]))*(0.0483);

                                        double ISR;
                                       if(sld>2600 && sld<5000){
                                          ISR = sld*0.03;
                                       }else{
                                            if(sld>5000 && sld<10000){
                                                ISR = sld*0.05;
                                         }else{
                                               ISR = sld*0.10;
                                          }
                                         }

                                    txtB4.setText(txtB4.getText()+"\nISR:  "+ISR+"\n");txtB4.setText(txtB4.getText()+"\nIGGS:  "+iggs+"\n");
                                     tot4=(Integer.parseInt(M[1][i]))+(Integer.parseInt(M[2][i]))+(Integer.parseInt(M[3][i]))+15000-ISR-iggs;
                                    txtB4.setText(txtB4.getText()+"\nTOTAL LIQUIDO:  "+tot4+"\n\n");
                                }else{
                                    txtB5.setText(txtB5.getText()+"\n NOMBRE:\t"+M[0][i]+"\n (+)SUELDO BASE:\t"+M[1][i]+"\n (+)DEDUCCIONES \t   "+M[2][i]+"\n(+)TOTAL PP\t "+M[3][i]+"\n(+)DEPARTAMENTO:\t 25,000");
                                    
                                    int sld = Integer.parseInt(M[1][i]);
                                        double iggs = (Integer.parseInt(M[1][i]))*(0.0483);

                                        double ISR;
                                       if(sld>2600 && sld<5000){
                                          ISR = sld*0.03;
                                       }else{
                                            if(sld>5000 && sld<10000){
                                                ISR = sld*0.05;
                                         }else{
                                               ISR = sld*0.10;
                                          }
                                         }

                                    txtB5.setText(txtB5.getText()+"\nISR:  "+ISR+"\n");txtB5.setText(txtB5.getText()+"\nIGGS:  "+iggs+"\n");
                                    tot5=(Integer.parseInt(M[1][i]))+(Integer.parseInt(M[2][i]))+(Integer.parseInt(M[3][i]))+25000-ISR-iggs;
                                    txtB5.setText(txtB5.getText()+"\nTOTAL LIQUIDO:  "+tot5+"\n\n");
                                }
                            }
                        }
                    }
                
            }
            
            
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtB1.setVisible(true);
        txtB2.setVisible(true);
        txtB3.setVisible(true);
        txtB4.setVisible(true);
        txtB5.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextArea txtA;
    private javax.swing.JTextArea txtB1;
    private javax.swing.JTextArea txtB2;
    private javax.swing.JTextArea txtB3;
    private javax.swing.JTextArea txtB4;
    private javax.swing.JTextArea txtB5;
    // End of variables declaration//GEN-END:variables
}
